apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ronballesteros-io
  description: ronballesteros-io-website
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: ronballesteros
  lifecycle: production
